routes/web.php
<?php
Route::get('/', function () {
    return view('client-views/try');
});

Route::get('/login', function () {
    return view('auth.login');
});

Route::get('/exercise',function () {
    return view('layouts.app');
});

Route::get('lessoncss/lessonhome', function () {
    return view('lessons.lessonhome');
});

Route::get('lessoncss/introduction', function () {
    return view('lessons.introduction');
});
Route::get('lessoncss/syntax', function () {
    return view('lessons.syntax');
});
Route::get('lessoncss/variable', function () {
    return view('lessons.variable');
});
Route::get('lessoncss/constant', function () {
    return view('lessons.constant');
});
Route::get('lessoncss/dtypes', function () {
    return view('lessons.dtypes');
});
Route::get('lessoncss/operator', function () {
    return view('lessons.operator');
});
Route::get('lessoncss/decision', function () {
    return view('lessons.decision');
});
Route::get('lessoncss/loop', function () {
    return view('lessons.loop');
});
Route::get('lessoncss/fixed', function () {
    return view('lessons.fixed');
});

Route::get('lessoncss/split', function () {
    return view('lessons.split');
});

Route::get('lessoncss/mySQL', function () {
    return view('lessons.mySQL');
});
Route::get('lessoncss/prep', function () {
    return view('lessons.prep');
});
Route::get('lessoncss/record', function () {
    return view('lessons.record');
});
Route::get('lessoncss/dml', function () {
    return view('lessons.dml');
});
Route::get('lessoncss/imp', function () {
    return view('lessons.imp');
});
Route::get('lessoncss/session', function () {
    return view('lessons.session');
});
Route::get('lessoncss/slide', function () {
    return view('lessons.slide');

});
Route::get('lessoncss/practice', function () {
    return view('lessons.practice');
});


Route::get('client/intro2', 'LessonController@lesson2');
Route::get('client/intro', 'LessonController@lesson1');
Route::get('client/intro3', 'LessonController@lesson3');
Route::get('client/chap1', 'LessonController@lesson4');
Route::get('client/chap2', 'LessonController@lesson5');
Route::get('client/chap3', 'LessonController@lesson6');
Route::get('client/chap4', 'LessonController@lesson7');
    /*function () {

    return view('client-views.intro');
});*/
// Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->get('logout', 'Auth\LoginController@logout')->name('auth.logout');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
$this->get('oauth2google', 'Auth\Oauth2Controller@oauth2google')->name('oauth2google');
$this->get('googlecallback', 'Auth\Oauth2Controller@googlecallback')->name('googlecallback');
$this->get('oauth2facebook', 'Auth\Oauth2Controller@oauth2facebook')->name('oauth2facebook');
$this->get('facebookcallback', 'Auth\Oauth2Controller@facebookcallback')->name('facebookcallback');
$this->get('oauth2github', 'Auth\Oauth2Controller@oauth2github')->name('oauth2github');
$this->get('githubcallback', 'Auth\Oauth2Controller@githubcallback')->name('githubcallback');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('auth.password.email');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');


    Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('tests', 'TestsController');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', ['uses' => 'UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'UserActionsController');
    Route::resource('topics', 'TopicsController');
    Route::post('topics_mass_destroy', ['uses' => 'TopicsController@massDestroy', 'as' => 'topics.mass_destroy']);
    Route::resource('questions', 'QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::resource('questions_options', 'QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::resource('results', 'ResultsController');
    Route::post('results_mass_destroy', ['uses' => 'ResultsController@massDestroy', 'as' => 'results.mass_destroy']);
    Route::resource('subtopics', 'SubtopicsController');
    Route::post('subtopics_mass_destroy', ['uses' => 'SubtopicsController@massDestroy', 'as' => 'subtopics.mass_destroy']);
    Route::resource('lessons', 'LessonController');
    Route::post('lessons_mass_destroy', ['uses' => 'LessonController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::get('/exercise', 'ExerciseController@index');
});

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lesson extends Model
{
    use SoftDeletes;

    protected $fillable = ['subtopic_id', 'topic_id','lesson_text'];

    public static function boot()
    {
        parent::boot();

        Lesson::observe(new \App\Observers\UserActionsObserver);
    }

    /**
     * Set to null if empty
     * @param $input
     */
    public function setTopicIdAttribute($input)
    {
        $this->attributes['topic_id'] = $input ? $input : null;
    }

    public function setSubTopicIdAttribute($input)
    {
        $this->attributes['subtopic_id'] = $input ? $input : null;
    }

    public function topic()
    {
        return $this->hasMany(Topic::class, 'topic_id')->withTrashed();
    }

    public function subtopic()
    {
        return $this->hasMany(SubTopic::class, 'subtopic_id')->withTrashed();
    }
}

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\Lesson;
use App\SubTopic;
use App\Topic;
use Illuminate\Http\Request;
use App\Http\Requests\StoreLessonsRequest;
use App\Http\Requests\UpdateLessonsRequest;


class LessonController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $lessons = Lesson::all();

        return view('lessons.index', compact('lessons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $relations = [
            'topics' => \App\Topic::get()->pluck('title', 'id')->prepend('Please select', ''),
            'subtopics' => \App\SubTopic::get()->pluck('title', 'id')->prepend('Please select', ''),
        ];
        return view('lessons.create', $relations);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreLessonsRequest $request)
    {
        Lesson::create($request->all());

        return redirect()->route('lessons.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $relations = [
            'topics' => \App\Topic::get()->pluck('title', 'id')->prepend('Please select', ''),
            'subtopics' => \App\SubTopic::get()->pluck('title', 'id')->prepend('Please select', ''),
        ];

        return view('lessons.show', compact('lesson'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lesson = Lesson::findOrFail($id);

        return view('lessons.edit', compact('lesson'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateLessonsRequest $request, $id)
    {
        $relations = [
            'topics' => \App\Topic::get()->pluck('title', 'id')->prepend('Please select', ''),
            'subtopics' => \App\SubTopic::get()->pluck('title', 'id')->prepend('Please select', ''),
        ];

        $lesson = Lesson::findOrFail($id);

        return view('lessons.show', compact('lesson') + $relations);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lesson = Lesson::findOrFail($id);
        $lesson->delete();

        return redirect()->route('lessons.index');
    }

    public function massDestroy(Request $request)
    {
        if ($request->input('ids')) {
            $entries = Lesson::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }
}

resources/views/lessons/LessonSidebar.blade.php
@inject('request', 'Illuminate\Http\Request')
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu"
            data-keep-expanded="false"
            data-auto-scroll="true"
            data-slide-speed="200">

            <li>
                <a>
                    <span class="title">Chapter 1</span>
                    <span class="fa fa-arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Introduction
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Syntax Overview
                            </span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a>
                    <span class="title">Chapter 2</span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Variables
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Constant
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Data Types
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Operator
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Decision Making
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Loop Types
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                MySQL
                            </span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a>
                    <span class="title">Chapter 3</span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                PHP Prep
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                MySQL Rec
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Import
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                DML
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('roles.index') }}">
                            <i class="fa fa-book"></i>
                            <span class="title">
                                Session
                            </span>
                        </a>
                    </li>
                </ul>
            </li>  

            <li>
                <a href="lessonhome">
                    <i class="fa fa-arrow-left"></i>
                    <span class="title">Back</span>
                </a>
            </li>
        </ul>
    </div>
</div>

resources/views/lessons/constant.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
    <title>PHP Online Editor</title>
    <link rel="stylesheet" id="font-awesome"  href="libs/font-awesome.min.css" type="text/css" media="all" />
    <script src="libs/jquery-2.1.4.min.js"></script>    
    
    <link rel="stylesheet"  href="css/php-einfach-online-php-editor.css" type="text/css" media="all" />
    <script type="text/javascript" src="../lessoncss/js/php-einfach-online-php-editor.js"></script>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="style2.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

    
<style>
body {
    font-family: Arial; font-size: 22px;
}

a {
    text-decoration: none;
    color: #20477a;
}

.ace_editor {
    font-size: 14px !important;
}
.split {
  height: 100%;
  width: 50%;
  position: fixed;
  z-index: 1;
  top: 0;
  overflow-x: hidden;
  padding-top: 20px;
  
  }
.splits {
  height: 100%;
  width: 50%;
  position: fixed;
  z-index: 1;
  top: 0;
  overflow-x: hidden;
  padding-top: 20px;
}
.left {
  left: 250px;
  width: 300px;
  position: absolute;

  
}
.right {
 position: absolute;
}
</style>
</head>
 
<body>

<div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar" >

            
            <div class="sidebar-header">
                <center>
                <a href="/"  role="button" style="background-color: black;"><h3>PHP Tutorial</h3></a>
                <center>
            </div>

             <ul class="list-unstyled components">
                <li>
                    <a href="lessonhome">
                       Home
                    </a></li>
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"> 
                        Chapter I
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="introduction">Introduction</a>
                        </li>
                        <li>
                            <a href="syntax"> Syntax Overview</a>
                        </li>


                    </ul>
               
    

                <li class="active">
                    <a href="#homeSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"> 
                        Chapter II
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu2">
                        <li>
                            <a href="variable">Variables</a>
                        </li>
                        <li class="btn-info"><strong><i>
                            <a href="constant"> Constant</a>
                        </li></i> </strong>
                        <li>
                            <a href="dtypes"> Data Types</a>
                        </li>
                        <li>
                            <a href="operator">Operator</a>
                        </li>
                         <li>
                    <a href="decision" >
                        Decision Making
                    </a></li>
                    <li>
                    <a href="loop" >
                        Loop Types
                    </a></li>
                    <li>
                    <a href="mySQL" >
                        My SQL
                    </a></li>
                    </ul>
                </li> </li>

                <li class="active">
                    <a href="#homeSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"> 
                        Chapter III
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu3">
                          <li>
                        <a href="prep" >
                        PHP Prep 
                    </a></li>
                      <li>
                        <a href="record" >
                        MySQL Rec 
                    </a></li>
                     <li>
                        <a href="imp" >
                        Import
                    </a></li>
                    <li>
                        <a href="dml" >
                       DML
                    </a></li>
                    <li>
                        <a href="session" >
                       Session
                    </a></li>
                    
                    </ul>
                </li>
                <li>
                        <a href="practice" class="btn btn-info btn-lg btn-dark" role="button" style="width: 250px;">Practice</a>
                    </li>
                    <li>
                        <a href="/tests" class="btn btn-info btn-lg btn-dark" role="button" style="width: 250px;">Take Exercise</a>
                    </li>
        </nav>
        <!-- Page Content  -->
         <div id="content" class="split left"  style="width: 750px; background-image:'client/img/lessons.jpg';">
            
<p><h1>PHP Tutorial: Constants</h1></p>
           <br><br> Constants are similar to variables except that they cannot be changed or undefined after they've been defined.<br><br>
Begin the name of your constant with a letter or an underscore.<br><br>
A constant is an identifier for a simple value. The value cannot be modified during the script's execution. A valid constant name starts with a letter or underscore (no dollar($) sign before the name) and by convention constant identifier are always uppercase.<br><br>
To create a constant, use the <b>define</b>() function:<br>
<b>define</b>(name, value, case-insensitive)<br><br>
Parameters:<br>
<b>name</b>: Specifies the name of the constant;
<b>value</b>: Specifies the value of the constant;
<b>case-insensitive</b>: Specifies whether the constant name should be case-insensitive. Default is <b>false</b>;<br><br>
The example below creates a constant with a <b>case-sensitive</b> name:<br>
<div  class="code" id="code_1" data-ace-editor-id="1"
    data-ace-editor-allow-execution="true" data-ace-editor-hide-vars="false" 
    data-ace-editor-script-name="page.php" data-ace-editor-default-get="" data-ace-editor-default-post="">
<pre class="editor" id="code_editor_1" >
&lt;?php
define("MSG", "Something!");
echo MSG;
</pre></div>

<br><br>The example below creates a constant with a <b>case-insensitive </b>name:<br>
<div  class="code" id="code_2" data-ace-editor-id="2"
    data-ace-editor-allow-execution="true" data-ace-editor-hide-vars="false" 
    data-ace-editor-script-name="page.php" data-ace-editor-default-get="" data-ace-editor-default-post="">
<pre class="editor" id="code_editor_2" >
&lt;?php
define("MSG", " Something!", true);
echo msg;
</pre></div>
<br><i>*No dollar sign ($) is necessary before the constant name.</i>

<br><br><h2>Differences between constants and variables are:</h2>
>>There is no need to write a dollar sign ($) before a constant, where as in Variable one has to write a dollar sign.<br>

>>Constants cannot be defined by simple assignment, they may only be defined using the define() function.<br>

>>Constants may be defined and accessed anywhere without regard to variable scoping rules.<br>

>>Once the Constants have been set, may not be redefined or undefined.<br>

<br><h2>Valid and invalid constant names</h2><br>
<div  class="code" 
    data-ace-editor-allow-execution="true" data-ace-editor-hide-vars="false" 
    data-ace-editor-script-name="page.php" data-ace-editor-default-get="" data-ace-editor-default-post="ooo">
<pre class="editor" 
<pre class="prettyprint notranslate prettyprinted" style="">/ Valid constant names
define("ONE",     "first thing");
define("TWO2",    "second thing");
define("THREE_3", "third thing");

// Invalid constant names
define("2TWO",    "second thing");
define("__THREE__", "third value"); </pre>
</div>

<script type='text/javascript' src='../lessoncss/libs/ace/ace.js'></script>
<script type='text/javascript' src='../lessoncss/libs/FileSaver.js'></script>
<script type='text/javascript' src='..lessoncss/js/php-einfach-online-php-editor.js'></script>

<script>
jQuery('div[data-ace-editor-id]').each(function() {
    var url='http://execute.php-einfach.de:9999/execute.php'; 
    //var url='proxy.php'; // In case the browser supports cross domain requests, you can use this proxy script to forward the requests over your own server
    var language = 'en'; //Choose 'de' for German
    new OnlinePHPEditor(this, language, url);
});
</script>
</div>

<!-- jQuery CDN - Slim version (=without AJAX) -->
    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>

               
        </div>
    </div>
<div>
    <h1 style="color: black; position: absolute; right: 130px; top: 10px;">Videos</h1>
<video style="width:320px; height:220px; position:relative; right: -1020px; top:50px;" controls >
  <source src="../lessoncss/vid4.mp4" type="video/mp4">
  </video>
</div>
</body>
</html>

resources/views/lessons/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Lessons</h3>
    
    {!! Form::model($lesson, ['method' => 'PUT', 'route' => ['lessons.update', $lesson->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.edit')
        </div>

        <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('lesson_text', 'Lesson text*', ['class' => 'control-label']) !!}
                    {!! Form::textarea('lesson_text', old('lesson_text'), ['class' => 'form-control ', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('lesson_text'))
                        <p class="help-block">
                            {{ $errors->first('lesson_text') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('code_snippet', 'Code snippet', ['class' => 'control-label']) !!}
                    {!! Form::textarea('code_snippet', old('code_snippet'), ['class' => 'form-control ', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('code_snippet'))
                        <p class="help-block">
                            {{ $errors->first('code_snippet') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/lessons/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Lessons</h3>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.view')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Chapter</th>
                    <td>{{ $lessons->topic->title}}</td></tr>
                        <tr>
                            <th>Topic</th>
                    <td>{{ $lessons->subtopic_id }}</td></tr>
                        <tr>
                            <th>Code Snippets</th>
                    <td>{{ $lessons->code_snippets }}</td></tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('lessons.index') }}" class="btn btn-default">@lang('quickadmin.back_to_list')</a>
        </div>
    </div>
@stop

resources/views/lessons/split.blade.php
<!DOCTYPE html>
<html>
<head>

/* Split the screen in half */
<style>.split {
  height: 100%;
  width: 50%;
  position: fixed;
  z-index: 1;
  top: 0;
  overflow-x: hidden;
  padding-top: 20px;
}

/* Control the left side */
.left {
  left: 0;
  background-color: #111;
}

/* Control the right side */
.right {
  right: 0;
  background-color: red;
}

/* If you want the content centered horizontally and vertically */
.centered {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}

/* Style the image inside the centered container, if needed */
.centered img {
  width: 150px;
  border-radius: 50%;
}
</style>

<body>
<div class="split left">
  <div class="centered">
    <img src="img_avatar2.png" alt="Avatar woman">
    <h2>Jane Flex</h2>
    <p>Some text.</p>
  </div>
</div>

<div class="split right">
  <div class="centered">
    <img src="img_avatar.png" alt="Avatar man">
    <h2>John Doe</h2>
    <p>Some text here too.</p>
  </div>
</div>
</body>
</head>
</html>